

INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NAMIBIANA','NAM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ANGOLESA','AGO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ARGELIANA','DZA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE BENNIN','BEN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BOTSWANESA','BWA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BURUNDESA','BDI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE CABO VERDE','CPV');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('COMORENSE','COM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CONGOLESA','COD');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MARFILEÑA','COG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CHADIANA','TCD');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE DJIBOUTI','DJI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('EGIPCIA','EGY');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ETIOPE','ETH');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GABONESA','GAB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GAMBIANA','GMB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GHANATA','GHA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GUINEA','GNB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GUINEA','GIN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GUINEA ECUATORIANA','GNQ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LIBIA','LBY');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('KENIANA','KEN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LESOTHENSE','LSO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LIBERIANA','LBR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MALAWIANA','MWI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MALIENSE','MLI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MARROQUI','MAR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MAURICIANA','MUS');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MAURITANA','MRT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MOZAMBIQUEÑA','MOZ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NIGERINA','NER');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NIGERIANA','NGA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CENTRO AFRICANA','CAF');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CAMERUNESA','CMR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TANZANIANA','TZA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('RWANDESA','RWA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DEL SAHARA','ESH');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE SANTO TOME','STP');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SENEGALESA','SEN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE SEYCHELLES','SYC');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SIERRA LEONESA','SLE');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SOMALI','SOM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SUDAFRICANA','ZAF');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SUDANESA','SDN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SWAZI','SWZ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TOGOLESA','TGO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TUNECINA','TUN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('UGANDESA','UGA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ZAIRANA','ZAR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ZAMBIANA','ZMB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE ZIMBAWI','ZWE');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ARGENTINA','ARG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BAHAMEÑA','BHS');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE BARBADOS','BRB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BELICEÑA','BLZ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BOLIVIANA','BOL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BRASILEÑA','BRA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CANADIENSE','CAN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('COLOMBIANA','COL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('COSTARRICENSE','CRI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CUBANA','CUB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CHILENA','CHL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DOMINICA','DMA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SALVADOREÑA','SLV');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESTADOUNIDENSE','USA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GRANADINA','VCT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GUATEMALTECA','GTM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BRITANICA','VGB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GUYANESA','GUY');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('HAITIANA','HTI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('HONDUREÑA','HND');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('JAMAIQUINA','JAM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MEXICANA','MEX');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NICARAGUENSE','NIC');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PANAMEÑA','PAN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PARAGUAYA','PRY');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PERUANA','PER');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PUERTORRIQUEÑA','PRI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DOMINICANA','DOM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SANTA LUCIENSE','LCA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SURINAMENSE','SUR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TRINITARIA','TTO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('URUGUAYA','URY');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('VENEZOLANA','VEN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('AMERICANA','USA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('AFGANA','AFG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DE BAHREIN','BHR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BHUTANESA','BTN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BIRMANA','BUR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NORCOREANA','PRK');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SUDCOREANA','KOR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CHINA','CHN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CHIPRIOTA','CYP');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ARABE','SAU');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('FILIPINA','PHL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('HINDU','IND');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('INDONESA','IDN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('IRAQUI','IRQ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('IRANI','IRN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ISRAELI','ISR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('JAPONESA','JPN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('JORDANA','JOR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CAMBOYANA','KHM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('KUWAITI','KWT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LIBANESA','LBN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MALASIA','MYS');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MALDIVA','MDV');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MONGOLESA','MNG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NEPALESA','NPL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('OMANESA','OMN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PAKISTANI','PAK');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DEL QATAR','QAT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SIRIA','SYR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LAOSIANA','LAO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SINGAPORENSE','SGP');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TAILANDESA','THA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TAIWANESA','TWN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('TURCA','TUR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NORVIETNAMITA','VNM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('YEMENI','YEM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ALBANESA','ALB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ALEMANA','DEU');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ANDORRANA','AND');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('AUSTRIACA','AUT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BELGA','BEL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BULGARA','BGR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('CHECOSLOVACA','CSK');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('DANESA','DNK');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('VATICANA','VAT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESPAÑOLA','ESP');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('FINLANDESA','FIN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('FRANCESA','FRA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('GRIEGA','GRC');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('HUNGARA','HUN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('IRLANDESA','IRL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ISLANDESA','ISL');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ITALIANA','ITA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LIECHTENSTENSE','LIE');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LUXEMBURGUESA','LUX');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MALTESA','MLT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MONEGASCA','MCO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NORUEGA','NOR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('HOLANDESA','NLD');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PORTUGUESA','PRT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BRITANICA','IOT');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SOVIETICA BIELORRUSA','BLR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SOVIETICA UCRANIANA','UKR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('RUMANA','ROM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SAN MARINENSE','SMR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SUECA','SWE');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SUIZA','CHE');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('YUGOSLAVA','YUG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('AUSTRALIANA','AUS');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('FIJIANA','FJI');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SALOMONESA','SLB');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('NAURUANA','NRU');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('PAPUENSE','PNG');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('SAMOANA','WSM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESLOVACA','SVK');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('BURKINA FASO','BFA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESTONIA','EST');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MICRONECIA','FSM');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('REINO UNIDO(DEPEN. TET. BRIT.)','GBD');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('REINO UNIDO(BRIT. DEL EXT.)','GBN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('REINO UNIDO(C. BRIT. DEL EXT.)','GBO');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('REINO UNIDO','GBR');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('KIRGUISTAN','KGZ');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('LITUANIA ','LTU');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MOLDOVIA, REPUBLICA DE','MDA');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('MACEDONIA','MKD');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESLOVENIA','SVN');
INSERT INTO Nacionalidad (etiqueta,clave) VALUES ('ESLOVAQUIA','XES');