
INSERT INTO entidadfederativa VALUES  (1  ,'Aguascalientes');
INSERT INTO entidadfederativa VALUES  (2  ,'Baja California');
INSERT INTO entidadfederativa VALUES  (3  ,'Baja California Sur');
INSERT INTO entidadfederativa VALUES  (4  ,'Campeche');
INSERT INTO entidadfederativa VALUES  (5  ,'Coahuila de Zaragoza');
INSERT INTO entidadfederativa VALUES  (6  ,'Colima');
INSERT INTO entidadfederativa VALUES  (7  ,'Chiapas');
INSERT INTO entidadfederativa VALUES  (8  ,'Chihuahua');
INSERT INTO entidadfederativa VALUES  (9  ,'Ciudad de México');
INSERT INTO entidadfederativa VALUES  (10     ,'Durango');
INSERT INTO entidadfederativa VALUES  (11     ,'Guanajuato');
INSERT INTO entidadfederativa VALUES  (12     ,'Guerrero');
INSERT INTO entidadfederativa VALUES  (13     ,'Hidalgo');
INSERT INTO entidadfederativa VALUES  (14     ,'Jalisco');
INSERT INTO entidadfederativa VALUES  (15     ,'México');
INSERT INTO entidadfederativa VALUES  (16     ,'Michoacán de Ocampo');
INSERT INTO entidadfederativa VALUES  (17     ,'Morelos');
INSERT INTO entidadfederativa VALUES  (18     ,'Nayarit');
INSERT INTO entidadfederativa VALUES  (19     ,'Nuevo León');
INSERT INTO entidadfederativa VALUES  (20     ,'Oaxaca');
INSERT INTO entidadfederativa VALUES  (21     ,'Puebla');
INSERT INTO entidadfederativa VALUES  (22     ,'Querétaro');
INSERT INTO entidadfederativa VALUES  (23     ,'Quintana Roo');
INSERT INTO entidadfederativa VALUES  (24     ,'San Luis Potosí');
INSERT INTO entidadfederativa VALUES  (25     ,'Sinaloa');
INSERT INTO entidadfederativa VALUES  (26     ,'Sonora');
INSERT INTO entidadfederativa VALUES  (27     ,'Tabasco');
INSERT INTO entidadfederativa VALUES  (28     ,'Tamaulipas');
INSERT INTO entidadfederativa VALUES  (29     ,'Tlaxcala');
INSERT INTO entidadfederativa VALUES  (30     ,'Veracruz de Ignacio de la Llave');
INSERT INTO entidadfederativa VALUES  (31     ,'Yucatán');
INSERT INTO entidadfederativa VALUES  (32     ,'Zacatecas');
