
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (1,4)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (2,5)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (3,4)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (4,2)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (5,2)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (6,3)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (7,5)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (8,3)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (9,4) 
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (10,3)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (11,5)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (12,3)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (13,5)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (14,1)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (15,4)
INSERT INTO Delegacion_Zona (id_Delegacion ,id_Zona) VALUES (16,2)