<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dispositivo extends \App\Entities\Dispositivo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'etiqueta', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'cantidad', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'tipoDispositivo', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'token', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'numeroActualizacion', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'puertaMercado', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'puertasPlazas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'tipoStatus', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'pruebas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'alertas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'negocio', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'motivosAltaBaja'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'etiqueta', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'cantidad', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'tipoDispositivo', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'token', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'numeroActualizacion', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'puertaMercado', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'puertasPlazas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'tipoStatus', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'pruebas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'alertas', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'negocio', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\Dispositivo' . "\0" . 'motivosAltaBaja'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dispositivo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtiqueta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtiqueta', []);

        return parent::getEtiqueta();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtiqueta($etiqueta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtiqueta', [$etiqueta]);

        return parent::setEtiqueta($etiqueta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDispositivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDispositivo', []);

        return parent::getTipoDispositivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDispositivo($tipoDispositivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDispositivo', [$tipoDispositivo]);

        return parent::setTipoDispositivo($tipoDispositivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroActualizacion', []);

        return parent::getNumeroActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroActualizacion($numeroActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroActualizacion', [$numeroActualizacion]);

        return parent::setNumeroActualizacion($numeroActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuertaMercado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuertaMercado', []);

        return parent::getPuertaMercado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuertaMercado($puertaMercado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuertaMercado', [$puertaMercado]);

        return parent::setPuertaMercado($puertaMercado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuertasPlazas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuertasPlazas', []);

        return parent::getPuertasPlazas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuertasPlazas($puertasPlazas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuertasPlazas', [$puertasPlazas]);

        return parent::setPuertasPlazas($puertasPlazas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoStatus', []);

        return parent::getTipoStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoStatus($tipoStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoStatus', [$tipoStatus]);

        return parent::setTipoStatus($tipoStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPruebas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPruebas', []);

        return parent::getPruebas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPruebas($pruebas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPruebas', [$pruebas]);

        return parent::setPruebas($pruebas);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlertas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlertas', []);

        return parent::getAlertas();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlertas($alertas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlertas', [$alertas]);

        return parent::setAlertas($alertas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegocio', []);

        return parent::getNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegocio($negocio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegocio', [$negocio]);

        return parent::setNegocio($negocio);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivosAltaBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivosAltaBaja', []);

        return parent::getMotivosAltaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivosAltaBaja($motivosAltaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivosAltaBaja', [$motivosAltaBaja]);

        return parent::setMotivosAltaBaja($motivosAltaBaja);
    }

}
