<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Encargado extends \App\Entities\Encargado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'nombre', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'apellidoPaterno', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'apellidoMaterno', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'telefono', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'extension', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'celular', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'correo', 'asociaciones', 'cadenas', 'negocios', 'plazas', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'tipoEncargado', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'motivosAltaBaja'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'nombre', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'apellidoPaterno', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'apellidoMaterno', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'telefono', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'extension', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'celular', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'correo', 'asociaciones', 'cadenas', 'negocios', 'plazas', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'tipoEncargado', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\Encargado' . "\0" . 'motivosAltaBaja'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Encargado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoPaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoPaterno', []);

        return parent::getApellidoPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoPaterno($apellidoPaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoPaterno', [$apellidoPaterno]);

        return parent::setApellidoPaterno($apellidoPaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoMaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoMaterno', []);

        return parent::getApellidoMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoMaterno($apellidoMaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoMaterno', [$apellidoMaterno]);

        return parent::setApellidoMaterno($apellidoMaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtension', []);

        return parent::getExtension();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtension($extension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtension', [$extension]);

        return parent::setExtension($extension);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', []);

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelular($celular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelular', [$celular]);

        return parent::setCelular($celular);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsociaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsociaciones', []);

        return parent::getAsociaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsociaciones($asociaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsociaciones', [$asociaciones]);

        return parent::setAsociaciones($asociaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCadenas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadenas', []);

        return parent::getCadenas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCadenas($cadenas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCadenas', [$cadenas]);

        return parent::setCadenas($cadenas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegocios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegocios', []);

        return parent::getNegocios();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegocios($negocios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegocios', [$negocios]);

        return parent::setNegocios($negocios);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlazas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlazas', []);

        return parent::getPlazas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlazas($plazas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlazas', [$plazas]);

        return parent::setPlazas($plazas);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivosAltaBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivosAltaBaja', []);

        return parent::getMotivosAltaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function addMotivoAltaBaja(\App\Entities\MotivoAltaBaja $motivoAltaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMotivoAltaBaja', [$motivoAltaBaja]);

        return parent::addMotivoAltaBaja($motivoAltaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivosAltaBaja($motivoAltaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivosAltaBaja', [$motivoAltaBaja]);

        return parent::setMotivosAltaBaja($motivoAltaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEncargado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEncargado', []);

        return parent::getTipoEncargado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEncargado($tipoEncargado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEncargado', [$tipoEncargado]);

        return parent::setTipoEncargado($tipoEncargado);
    }

}
