<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OficioIncorporacion extends \App\Entities\OficioIncorporacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'id', 'negocio', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'documento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'nombreDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'extensionDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'mimeTypeDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'tamanoDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'fechaAltaDocumento'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'id', 'negocio', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'documento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'nombreDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'extensionDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'mimeTypeDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'tamanoDocumento', '' . "\0" . 'App\\Entities\\OficioIncorporacion' . "\0" . 'fechaAltaDocumento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OficioIncorporacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegocio', []);

        return parent::getNegocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegocio($negocio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegocio', [$negocio]);

        return parent::setNegocio($negocio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', []);

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', [$documento]);

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDocumento', []);

        return parent::getNombreDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDocumento($nombreDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDocumento', [$nombreDocumento]);

        return parent::setNombreDocumento($nombreDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtensionDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtensionDocumento', []);

        return parent::getExtensionDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtensionDocumento($extensionDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtensionDocumento', [$extensionDocumento]);

        return parent::setExtensionDocumento($extensionDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMimeTypeDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMimeTypeDocumento', []);

        return parent::getMimeTypeDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setMimeTypeDocumento($mimeTypeDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMimeTypeDocumento', [$mimeTypeDocumento]);

        return parent::setMimeTypeDocumento($mimeTypeDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamanoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamanoDocumento', []);

        return parent::getTamanoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamanoDocumento($tamanoDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamanoDocumento', [$tamanoDocumento]);

        return parent::setTamanoDocumento($tamanoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAltaDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAltaDocumento', []);

        return parent::getFechaAltaDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAltaDocumento($fechaAltaDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAltaDocumento', [$fechaAltaDocumento]);

        return parent::setFechaAltaDocumento($fechaAltaDocumento);
    }

}
