<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Informe extends \App\Entities\Informe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'contenido', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'numeroDetenidos', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'entrevistados', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'entrevistadores', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'razon', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'reporta', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'participacion', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'tiempoRespuesta', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'folioPap', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'folioSip'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'contenido', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'numeroDetenidos', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'entrevistados', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'entrevistadores', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'razon', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'reporta', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'participacion', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'tiempoRespuesta', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'folioPap', '' . "\0" . 'App\\Entities\\Informe' . "\0" . 'folioSip'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Informe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido($contenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDetenidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDetenidos', []);

        return parent::getNumeroDetenidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDetenidos($numeroDetenidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDetenidos', [$numeroDetenidos]);

        return parent::setNumeroDetenidos($numeroDetenidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlarma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlarma', []);

        return parent::getAlarma();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlarma($alarma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlarma', [$alarma]);

        return parent::setAlarma($alarma);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrevistados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrevistados', []);

        return parent::getEntrevistados();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrevistados($entrevistados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrevistados', [$entrevistados]);

        return parent::setEntrevistados($entrevistados);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrevistadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrevistadores', []);

        return parent::getEntrevistadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrevistadores($entrevistadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrevistadores', [$entrevistadores]);

        return parent::setEntrevistadores($entrevistadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazon', []);

        return parent::getRazon();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazon($razon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazon', [$razon]);

        return parent::setRazon($razon);
    }

    /**
     * {@inheritDoc}
     */
    public function getReporta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReporta', []);

        return parent::getReporta();
    }

    /**
     * {@inheritDoc}
     */
    public function setReporta($reporta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReporta', [$reporta]);

        return parent::setReporta($reporta);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipacion', []);

        return parent::getParticipacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipacion($participacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipacion', [$participacion]);

        return parent::setParticipacion($participacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempoRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempoRespuesta', []);

        return parent::getTiempoRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempoRespuesta($tiempoRespuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempoRespuesta', [$tiempoRespuesta]);

        return parent::setTiempoRespuesta($tiempoRespuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolioPap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolioPap', []);

        return parent::getFolioPap();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolioPap($folioPap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolioPap', [$folioPap]);

        return parent::setFolioPap($folioPap);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolioSip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolioSip', []);

        return parent::getFolioSip();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolioSip($folioSip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolioSip', [$folioSip]);

        return parent::setFolioSip($folioSip);
    }

}
