<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Direccion extends \App\Entities\Direccion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'callePrincipal', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'calle1', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'calle2', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'numeroInterior', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'numeroExterior', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'edificio', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'tipoAsentamiento', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'nombreAsentamiento', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'colonia', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'codigoPostal'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'callePrincipal', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'calle1', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'calle2', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'numeroInterior', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'numeroExterior', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'edificio', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'tipoAsentamiento', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'nombreAsentamiento', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'colonia', '' . "\0" . 'App\\Entities\\Direccion' . "\0" . 'codigoPostal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Direccion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCallePrincipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCallePrincipal', []);

        return parent::getCallePrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCallePrincipal($callePrincipal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCallePrincipal', [$callePrincipal]);

        return parent::setCallePrincipal($callePrincipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle1', []);

        return parent::getCalle1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle1($calle1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle1', [$calle1]);

        return parent::setCalle1($calle1);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle2', []);

        return parent::getCalle2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle2($calle2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle2', [$calle2]);

        return parent::setCalle2($calle2);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroInterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroInterior', []);

        return parent::getNumeroInterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroInterior($numeroInterior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroInterior', [$numeroInterior]);

        return parent::setNumeroInterior($numeroInterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroExterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroExterior', []);

        return parent::getNumeroExterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroExterior($numeroExterior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroExterior', [$numeroExterior]);

        return parent::setNumeroExterior($numeroExterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdificio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdificio', []);

        return parent::getEdificio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdificio($edificio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdificio', [$edificio]);

        return parent::setEdificio($edificio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoAsentamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoAsentamiento', []);

        return parent::getTipoAsentamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoAsentamiento($tipoAsentamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoAsentamiento', [$tipoAsentamiento]);

        return parent::setTipoAsentamiento($tipoAsentamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAsentamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAsentamiento', []);

        return parent::getNombreAsentamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreAsentamiento($nombreAsentamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreAsentamiento', [$nombreAsentamiento]);

        return parent::setNombreAsentamiento($nombreAsentamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getColonia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColonia', []);

        return parent::getColonia();
    }

    /**
     * {@inheritDoc}
     */
    public function setColonia($colonia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColonia', [$colonia]);

        return parent::setColonia($colonia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

}
