<?php

namespace DoctrineProxies\__CG__\App\Entities\UsuariosApp;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioApp extends \App\Entities\UsuariosApp\UsuarioApp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'id', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'remember_token', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'usuario', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'password', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'email', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'nombre', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'apellidoPaterno', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'apellidoMaterno', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'institucionLabora', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'permisos', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'status', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'motivoBaja', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'motivoAlta'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'id', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'remember_token', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'usuario', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'password', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'email', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'nombre', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'apellidoPaterno', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'apellidoMaterno', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'institucionLabora', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'permisos', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'fechaAlta', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'status', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'motivoBaja', '' . "\0" . 'App\\Entities\\UsuariosApp\\UsuarioApp' . "\0" . 'motivoAlta'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioApp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifierName', []);

        return parent::getAuthIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifier', []);

        return parent::getAuthIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthPassword', []);

        return parent::getAuthPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$value]);

        return parent::setRememberToken($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberTokenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberTokenName', []);

        return parent::getRememberTokenName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoPaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoPaterno', []);

        return parent::getApellidoPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoPaterno($apellidoPaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoPaterno', [$apellidoPaterno]);

        return parent::setApellidoPaterno($apellidoPaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoMaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoMaterno', []);

        return parent::getApellidoMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoMaterno($apellidoMaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoMaterno', [$apellidoMaterno]);

        return parent::setApellidoMaterno($apellidoMaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstitucionLabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstitucionLabora', []);

        return parent::getInstitucionLabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstitucionLabora($institucionLabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstitucionLabora', [$institucionLabora]);

        return parent::setInstitucionLabora($institucionLabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivoBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivoBaja', []);

        return parent::getMotivoBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivoBaja($motivoBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivoBaja', [$motivoBaja]);

        return parent::setMotivoBaja($motivoBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivoAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivoAlta', []);

        return parent::getMotivoAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivoAlta($motivoAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivoAlta', [$motivoAlta]);

        return parent::setMotivoAlta($motivoAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermisos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermisos', []);

        return parent::getPermisos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermisos($permisos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermisos', [$permisos]);

        return parent::setPermisos($permisos);
    }

}
