<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MotivoAltaBaja extends \App\Entities\MotivoAltaBaja implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'id', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'contenido', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'tipo', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'usuario', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'fechaAlta', 'usuarios', 'usuariosPublico', 'usuariosMobile', 'encargados', 'asociaciones', 'cadenas', 'dispositivos', 'negocios', 'plazas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'id', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'contenido', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'tipo', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'usuario', '' . "\0" . 'App\\Entities\\MotivoAltaBaja' . "\0" . 'fechaAlta', 'usuarios', 'usuariosPublico', 'usuariosMobile', 'encargados', 'asociaciones', 'cadenas', 'dispositivos', 'negocios', 'plazas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MotivoAltaBaja $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido($contenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', []);

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarios($usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarios', [$usuarios]);

        return parent::setUsuarios($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariosPublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariosPublico', []);

        return parent::getUsuariosPublico();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariosPublico($usuariosPublico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariosPublico', [$usuariosPublico]);

        return parent::setUsuariosPublico($usuariosPublico);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariosMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariosMobile', []);

        return parent::getUsuariosMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariosMobile($usuariosMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariosMobile', [$usuariosMobile]);

        return parent::setUsuariosMobile($usuariosMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlarmas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlarmas', []);

        return parent::getAlarmas();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlarmas($alarmas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlarmas', [$alarmas]);

        return parent::setAlarmas($alarmas);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsociaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsociaciones', []);

        return parent::getAsociaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsociaciones($asociaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsociaciones', [$asociaciones]);

        return parent::setAsociaciones($asociaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCadenas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadenas', []);

        return parent::getCadenas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCadenas($cadenas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCadenas', [$cadenas]);

        return parent::setCadenas($cadenas);
    }

    /**
     * {@inheritDoc}
     */
    public function getDispositivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDispositivos', []);

        return parent::getDispositivos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDispositivos($dispositivos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDispositivos', [$dispositivos]);

        return parent::setDispositivos($dispositivos);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncargados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncargados', []);

        return parent::getEncargados();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncargados($encargados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncargados', [$encargados]);

        return parent::setEncargados($encargados);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegocios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegocios', []);

        return parent::getNegocios();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegocios($negocios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegocios', [$negocios]);

        return parent::setNegocios($negocios);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlazas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlazas', []);

        return parent::getPlazas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlazas($plazas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlazas', [$plazas]);

        return parent::setPlazas($plazas);
    }

}
